[package]
name = "spacebuild"
version = "0.1.0"
authors = ["Pierre-Alexandre Goya <pierre.alexandre.goya@gmail.com>"]
edition = "2021"

[lib]
name = "spacebuild"
doctest = false

[dependencies]
bincode = "1.3.3"
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"]}
futures = "0.3.31"
futures-time = "3.0.0"
http-body-util = "0.1.2"
hyper = {version = "1.5.2", features = ["server", "client", "http1"]}
hyper-rustls = {version = "0.27.5", features = ["native-tokio"]}
hyper-tungstenite = "0.17.0"
hyper-util = {version = "0.1.10", features = ["full"]}
is_printable = "0.0.11"
itertools = "0.14.0"
log = { version = "0.4.22"}
rand = "0.8.5"
rand_chacha = "0.3.1"
regex = "1.11.1"
rstar = "0.12.2"
rustls = { version = "0.23.20"}
rustls-native-certs = { version = "0.8.1"}
rustls-pemfile = { version = "2.2.0"}
rustls-pki-types = { version = "1.10.1"}
scilib = "1.0.0"
scopeguard = "1.2.0"
serde = { version = "1.0.217", features = ["derive"]}
serde_json = "1.0.134"
sqlx = { version = "0.8.2", features = ["sqlite", "runtime-tokio"]}
thiserror = "2.0.9"
tokio = { version = "1.42.0", features = ["full"]}
tokio-rustls = { version = "0.26.1"}
tokio-stream = "0.1.17"
tokio-tungstenite = {version = "0.26.1", features = ["rustls"]}
uuid = {version = "1.11.0", features = ["v4","fast-rng","macro-diagnostics","serde"]}
webpki = { version = "0.22.4", features = ["alloc"]}
webpki-roots = { version = "0.26.7"}

[dev-dependencies]
test-helpers-async = "0.2.3"
anyhow = "1.0.95"
common = {path = "../common", version = "0.1.0"}
