name: Siege & Publish
'on':
  push:
    branches: release

jobs:
  server-build-release:
    name: Server Build Release
    strategy:
        matrix:
          os:
            - ubuntu-24.04
            - windows-2022
            - macos-15
    runs-on: ${{ matrix.os }}
    steps:
        - name: 'Checkout'
          uses: actions/checkout@master

        - name: Build Library Release
          uses: actions-rs/cargo@v1
          with:
            command: build
            args: '-p spacebuild -r'

        - name: Build Server Release
          uses: actions-rs/cargo@v1
          with:
            command: build
            args: '-p spacebuild-server -r'
        - name: Build Siege Release
          uses: actions-rs/cargo@v1
          with:
                command: build
                args: '-p spacebuild-siege -r'

        - name: Install SpaceBuild Server
          uses: actions-rs/cargo@v1
          with:
                command: install
                args: '--path server --root .'
        - name: Install SpaceBuild Siege
          uses: actions-rs/cargo@v1
          with:
                command: install
                args: '--path siege --root .'
        - name: 'Upload Server/Siege Release ${{matrix.os}}'
          uses: actions/upload-artifact@v4
          with:
                name: 'bins-release-${{ matrix.os }}'
                path: bin/*
                if-no-files-found: error

  client-export-release:
    name: Client Build Release
    runs-on: ubuntu-24.04
    env:
      GODOT_VERSION: dev6
      EXPORT_NAME: spacebuild
      PROJECT_PATH: godot
    strategy:
      matrix:
        channel:
          - windows
          - macos
          - linux
          - webgl
    container:
      image: 'prusten/godot-44-ci:dev6'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/4.4.${GODOT_VERSION} \
          ~/.local/share/godot/export_templates/4.4.${GODOT_VERSION}
          mkdir -v -p "${PROJECT_PATH}/build/${{ matrix.channel }}"

      - name: Build Client Release
        id: build-client
        run: |
            EXPORT_DIR="build/${{ matrix.channel }}"

            cd "$PROJECT_PATH" || exit

            case "${{ matrix.channel }}" in
                "windows")
                    EXPORT_FILE="$EXPORT_DIR/${EXPORT_NAME}.exe"
                    echo "target=$EXPORT_FILE" >> $GITHUB_OUTPUT
                    ;;
                "linux")
                    EXPORT_FILE="$EXPORT_DIR/${EXPORT_NAME}.x86_64"
                    echo "target=$EXPORT_FILE" >> $GITHUB_OUTPUT
                    ;;
                "macos")
                    EXPORT_FILE="$EXPORT_DIR/${EXPORT_NAME}.zip"
                    echo "target=$EXPORT_FILE" >> $GITHUB_OUTPUT
                    ;;
                "webgl")
                    EXPORT_FILE="$EXPORT_DIR/index.html"
                    echo "target=$EXPORT_DIR/*" >> $GITHUB_OUTPUT
                    ;;
                *)
                    echo "Canal inconnu : ${{ matrix.channel }}"
                    exit 1
                    ;;
            esac

            echo "$EXPORT_FILE"
            godot --headless --verbose --export-release "${{ matrix.channel }}" "$EXPORT_FILE"

      - name: Upload Client
        uses: actions/upload-artifact@v4
        with:
            name: 'client-release-${{matrix.channel}}'
            path: "${{ env.PROJECT_PATH }}/${{ steps.build-client.outputs.target }}"
            if-no-files-found: error

  siege:
    name: Siege Test
    needs: server-build-release
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - windows-2022
          - macos-15
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Checkout ${{ github.repositoryUrl }} ${{ github.base_ref }}'
        uses: actions/checkout@master

      - name: 'Get bins-release-${{ matrix.os }}'
        uses: actions/download-artifact@v4
        with:
            name: 'bins-release-${{ matrix.os }}'
            path: bin

      - name: Create Crypto Files from Env
        shell: pwsh
        run: >
          Out-File -FilePath cert.pem -InputObject
          "${{vars.SPACEBUILD_SERVER_CERT }}"

          Out-File -FilePath key.pem -InputObject "${{vars.SPACEBUILD_SERVER_KEY
          }}"

          Out-File -FilePath ca_cert.pem -InputObject
          "${{vars.SPACEBUILD_CA_CERT }}"

      - name: Chmod
        if: ${{ contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos') }}
        run: chmod 755 bin/*
      - name: Extend PATH
        shell: pwsh
        run: >
          (Get-Item bin).FullName | Out-File -FilePath "$Env:GITHUB_PATH"
          -Append

      - name: Launch Server and Siege TLS
        shell: pwsh
        env:
          RUST_LOG: INFO
        run: >
          $process1 = Start-Process -FilePath "spacebuild-server" -ArgumentList
          "--tls", "cert.pem", "key.pem"
          -NoNewWindow -PassThru

          if (-not $process1) { exit 1 }

          Start-Sleep -Seconds 5

          $process2 = Start-Process -FilePath "spacebuild-siege" -ArgumentList
          "--tls", "ca_cert.pem" -NoNewWindow -PassThru

          if (-not $process2) { $process1.WaitForExit(); exit 1 }

          $process2.WaitForExit()

          $exitCode2 = $process2.ExitCode

          Stop-Process -Id $process1.Id

          if ($exitCode2 -ne 0) { exit 1 }

          exit 0

      - shell: pwsh
        id: get-channel
        run: |
            $channel = "${{ matrix.os }}" -split '-' | Select-Object -First 1
            $extension = if ($channel -eq "windows") { ".exe" } else { "" }
            $channel = if ($channel -eq "ubuntu") { "linux" } else { $channel }
            "channel=$channel" | Out-File -FilePath $Env:GITHUB_OUTPUT
            "extension=$extension" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append

      - name: Upload Tested Server Bin
        uses: actions/upload-artifact@v4
        with:
            name: server-release-${{steps.get-channel.outputs.channel}}
            path: bin/spacebuild-server${{steps.get-channel.outputs.extension}}

  publish-itchio:
    name: Publish ItchIO
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        channel:
          - windows
          - macos
          - linux
          - webgl
    needs: [siege, client-export-release]
    steps:
      - name: 'Get server-release-${{ matrix.channel }}'
        uses: actions/download-artifact@v4
        if: ${{ matrix.channel != 'webgl' }}
        with:
          name: 'server-release-${{ matrix.channel }}'
          path: spacebuild

      - name: 'Get client-release-${{ matrix.channel }}'
        uses: actions/download-artifact@v4
        with:
          name: 'client-release-${{ matrix.channel }}'
          path: spacebuild

      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: 'spacebuild'
          itchUsername: ${{secrets.ITCHIO_USERNAME}}
          itchGameId: ${{ secrets.ITCHIO_GAME }}
          buildChannel: ${{ matrix.channel }}
